### PR TITLE
Add serial part typization in version 1.1.0 due to legacy dependencie…

### PR DESCRIPTION
**Pull request by bs-jokri**
…s to this model

### CODE REVIEW

**Comment by jacewski-bosch** [comment]
@bs-jokri I have checked this is the right version and content looks fine as well. Thanks for adding.

**Comment by jacewski-bosch** [comment]
@bs-jokri should we also update Release Notes?

**Comment by bs-jokri** [comment]
@jacewski-bosch of course. I added an entry for 1.1.0 to the release notes. Thanks for the hint

**Comment by bs-jokri** [comment]
@jacewski-bosch are we good to merge?

**Comment by jacewski-bosch** [comment]
yes, please merge. Thanks!

**Pull request merged**
