### PR TITLE
Bugfix in example for quality Task

### PR DESCRIPTION
**Pull request by marcoGrebe**
bugfix: the date in the example does not match the schema.json of the submodel

### CODE REVIEW

**Comment by catroest** [comment]
Hi, shouldn't then the turtle example be changed (and then the json updated)?

**Comment by agg3fe** [comment]
@marcoGrebe value should be corrected in .ttl file.

**Review by agg3fe — CHANGES_REQUESTED** [review]
please make change in turtle file.

**Comment by TorstenHirsch** [comment]
@agg3fe  Hi Sahil, should I do here anything?

**Comment by TorstenHirsch** [comment]
Please add T00:00:00 to fix the bug - unfortunately I cannot contribute :-(

**Comment by agg3fe** [comment]
> @agg3fe Hi Sahil, should I do here anything?

Yes. The example value should be fixed in .ttl file here https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.quality_task/1.0.0/QualityTask.ttl#L51, and not in json file directly. After that json file should be regenerated.

**Pull request closed without merging**
