### PR TITLE
Fix: Updated samm cli to 2.9.0 and AME version to 5.6.0

### PR DESCRIPTION
**Pull request by agg3fe**
## Description
updated samm cli to 2.9.0 and AME version to 5.6.0

### CODE REVIEW

**Comment by agg3fe** [comment]
Not to be merged for now.

**Review by jSchuetz88 — APPROVED** [review]
Thank you for the update @agg3fe . We run into some issues / bugs with the generated AASX-files, which should be fixed with SAMM CLI v2.9.0 after a re-generation.

Eventually we should consider, to update "bammVersion" to "sammVersion" of the action-scripts, but as it does not affect the functionality, it would only be a not-mandatory patch.

**Comment by jSchuetz88** [comment]
@agg3fe 
It seems, there was an bugfix which fixed a second bug of the AASX serialization: https://github.com/eclipse-esmf/esmf-sdk/pull/632
But no new release so far.

**Comment by jSchuetz88** [comment]
As this PR is outdated and the contents have been merged within an other PR, I close this PR.

**Pull request closed without merging**
