### PR TITLE
Add Abstract Identifier and CatenaXIdentifier

### PR DESCRIPTION
**Pull request by jacewski-bosch**
## Description

General technical proposal for making dataspace specific identifiers more abstract.

Related to  #103 #105 

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  BAMM CLI is available [here](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html) and in [GitHub](https://github.com/OpenManufacturingPlatform/sds-sdk/releases)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "name" and "description"** in English language. 
- [ ] **no duplicate names or preferredNames** within an Aspect (e.g. a Property and the referenced Characteristic should not have the same name)
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the BAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/v1.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 
- [ ] all contributors to this model are mentioned in copyright header of model file

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [ ] All required reviewers have approved this PR (see reviewers section)
- [ ] The new aspect (version) will be implemented by at least one data provider
- [ ] The new aspect (version) will be consumed by at least one data consumer
- [ ] There exists valid test data
- [ ] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [ ] The model has at least version '1.0.0'

### CODE REVIEW

**Comment by jacewski-bosch** [comment]
couldn't validate locally but still was able to generate sample json payload that looked like this:
```json
{
  "identifier" : {
    "value" : "urn:uuid:30bbcECc-b0Ff-d3E2-BAfE-f9D3edef478B",
    "@type" : "CatenaXIdentifier"
  }
}
```
might be a bug in samm-CLI related to regular expressions.

**Comment by jacewski-bosch** [comment]
Generally anything in the shared namespace shouldn't include Aspect elements.

**Comment by bs-jokri** [comment]
FYI @arnoweiss WDYT. Lets discuss approach here.

**Comment by arnoweiss** [comment]
The result looks a lot like what we're after. We should check out if the artifact-generator chokes as there's some SAMM-elements that I'm not sure were used by any aspect before.

**Comment by bs-jokri** [comment]
@jacewski-bosch need to close and reopen to test fix for validation notification

**Comment by arnoweiss** [comment]
It was decided a while ago to not further pursue this PR as it's effects would be massive across the industry core and the use is marginal.

**Pull request closed without merging**
