### PR TITLE
Add template for standardization issue

### PR DESCRIPTION
**Pull request by bs-jokri**
## Description
Adds a new issue template to transfer a model into status standardize
@arnoweiss wdyt?

### CODE REVIEW

**Comment by arnoweiss** [comment]
Looks pretty complete to me. Might it make sense to think about automating this whole procedure?

**Comment by bs-jokri** [comment]
@arnoweiss automation is a good idea in any case. How would you envision an automation? Something like, if all MS1 checks are approved the status is automatically changend in a PR And the change is merged right away?

**Comment by arnoweiss** [comment]
Something a little different. This is the process that we want, right?

1. Model passes through sldt-semantic-models process.
2. Standardization in CX e.V. is started.
3. Standardization in CX e.V is achieved.
4. sldt-semantic-model updates status of aspect to "standardized"

As everything after step 1 is in someone else's responsibility, it'd be great if this repo could notice that step 3 is done and execute step 4 automatically.

**Comment by catroest** [comment]
Please note that model in a specific version ist standardized. So will this be a new line in the metadata.json extending the existing: { "status" : "release"}?

**Comment by bs-jokri** [comment]
> Please note that model in a specific version ist standardized. So will this be a new line in the metadata.json extending the existing: { "status" : "release"}?

Yes, the status "standardize" will come after a model is in status "release"

**Pull request merged**
