### PR TITLE
feat: add aspect model for Material Flow Simulation Result

### LINKED ISSUE #133: [New Model]: SimResult
## Model Description

Das SimResult Datenmodell von Online Control and Simulation(OSim) beschreibt die Simulationsergebnisse, welche zwischen OSim Partnern ausgetauscht werden.
Ein Simulationsergebnis besteht aus einem oder mehreren Shipments. Ein Shipment besteht aus mehreren Handling Units. Eine Handling Unit enthält mehrere Material Batches.

## Relevant Standards
None

## Example Data

```xml
<?xml version="1.0" encoding="utf-8"?>
<simulation_run>
    <simulation_timestamp>2023-03-24T09:15:24.000Z</simulation_timestamp>
    <simulation_data_quality>0</simulation_data_quality>
    <simulation_status>2</simulation_status>
    <simulation_comment>successful simulation</simulation_comment>
    <simulation_expiration_timestamp>2023-03-25T21:15:24.000Z</simulation_expiration_timestamp>
    <simulation_run_id>0fece4b8-c8d1-4180-8587-1a9caca6d67e</simulation_run_id>
    <simulation_owner>LOG_DE_07</simulation_owner>
    <simulation_description>Please simulate asap</simulation_description>
    <shipments>
        <shipment>
            <shipment_id>DE515151</shipment_id>
            <shipment_destination>DE-Werk-76</shipment_destination>
            <shipment_destination_timestamp>2023-04-19T09:00:00.000Z</shipment_destination_timestamp>
            <shipment_recipient>DE-Werk-76</shipment_recipient>
            <shipment_recipient_timestamp_planned>2023-04-17T17:00:00.000Z</shipment_recipient_timestamp_planned>
            <shipment_splitting_allowed>true</shipment_splitting_allowed>
            <shipment_logistics>DE-Log-07</shipment_logistics>
            <shipment_preceding>DE-Werk-42</shipment_preceding>
            <handling_units>
                <handling_unit>
                    <handling_unit_id>HUT_1</handling_unit_id>
                    <hut_name>Pallette</hut_name>
                    <handling_unit_volume>1</handling_unit_volume>
                    <handling_unit_weight>189</handling_unit_weight>
                    <handling_unit_amount>1</handling_unit_amount>
                    <material_batches>
                        <material_batch>
                            <batch_id>Batch_1</batch_id>
                            <material_number>KK1000GR</material_number>
                            <material_name>KK1000GR-Gehäuse-Rot</material_name>
                            <material_hazardous_goods>false</material_hazardous_goods>
                            <batch_expiration_timestamp>2024-08-22T16:00:00.000Z</batch_expiration_timestamp>
                            <batch_quantity>50</batch_quantity>
                            <batch_uom>Stk</batch_uom>
                            <batch_number>45</batch_number>
                            <batch_order_id>Order-0001</batch_order_id>
                        </material_batch>
                        <material_batch>
                            <batch_id>Batch_2</batch_id>
                            <material_number>KK1000GG</material_number>
                            <material_name>KK1000GG-Gehäuse-Grün</material_name>
                            <material_hazardous_goods>false</material_hazardous_goods>
                            <batch_expiration_timestamp>2024-08-23T15:59:59.995Z</batch_expiration_timestamp>
                            <batch_quantity>25</batch_quantity>
                            <batch_uom>Stk</batch_uom>
                            <batch_number>46</batch_number>
                            <batch_order_id>Order-0001</batch_order_id>
                        </material_batch>
                        <material_batch>
                            <batch_id>Batch_3</batch_id>
                            <material_number>KK1000GB</material_number>
                            <material_name>KK1000GB-Gehäuse-Blau</material_name>
                            <material_hazardous_goods>false</material_hazardous_goods>
                            <batch_expiration_timestamp>2024-08-24T15:59:59.995Z</batch_expiration_timestamp>
                            <batch_quantity>25</batch_quantity>
                            <batch_uom>Stk</batch_uom>
                            <batch_number>47</batch_number>
                            <batch_order_id>Order-0001</batch_order_id>
                        </material_batch>
                    </material_batches>
                </handling_unit>
            </handling_units>
        </shipment>
    </shipments>
</simulation_run>
```

## MS1 Criteria

- [x] The proposed aspect model does not exist already
- [x] The proposed aspect model does not extend an existing aspect but introduces completely new functionality
- [x] The proposal references a Catena-X use case
- [x] Relevant standards are mentioned/linked
- [x] A first draft of the data structure is provided in an example

### PR DESCRIPTION
**Pull request by dominikoeh**
adds the initial version of the Material Flow Simulation Result aspect model

## Description

 -->

Closes #133

## MS2 Criteria
(to be filled out by PR reviewer)
- [ ] the model **validates** with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check  (e.g., 'java -jar bamm-cli.jar -i \<path-to-aspect-model\> -v ). The  BAMM CLI is available [here](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html) and in [GitHub](https://github.com/OpenManufacturingPlatform/sds-sdk/releases)
- [ ] use **Camel-Case** (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [ ] the identifiers for all model elements **start with a capital letter** except for properties
- [ ] the identifier for **properties starts with a small letter**
- [ ] all model elements **at least contain the fields "name" and "description"** in English language. 
- [ ] **no duplicate names or preferredNames** within an Aspect (e.g. a Property and the referenced Characteristic should not have the same name)
- [ ] the versioning in the URN **follows semantic versioning**, where minor version bumps are backwards compatible and major version bumps are not backwards compatible. 
- [ ] use **abbreviations only when necessary** and if these are sufficiently common
- [ ] **avoid redundant prefixes in property names** (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties `DismantlerId` and `DismantlerName` use an Entity `Dismantler` with the properties `name` and `id` or use a URN like `io.catenax.dismantler:0.0.1`)
- [ ] fields `preferredName` and `description` are not the same
- [ ] **`preferredName` should be human readable** and follow normal orthography (e.g., no camel case but normal word separation)
- [ ] name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [ ] units are referenced from the BAMM unit catalog whenever possible
- [ ] **use constraints** to make known constraints from the use case explicit in the aspect model 
- [ ] when relying on **external standards**, they are referenced through a **"see"** element
- [ ] all properties with an [simple type](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/v1.0.0/datatypes.html) have an example value
- [ ] metadata.json exists with status "release"
- [ ] file RELEASE_NOTES.md exists and contains entries for proposed model changes 

## MS3 Criteria
(to be filled out by semantic modeling team before merge to main-branch)
- [x] All required reviewers have approved this PR (see reviewers section)
- [x] The new aspect (version) will be implemented by at least one data provider
- [x] The new aspect (version) will be consumed by at least one data consumer
- [x] There exists valid test data
- [x] In case of a new (incompatible) major version to an existing version, a migration strategy has been developed
- [x] The model has at least version '1.0.0'

### CODE REVIEW

**Comment by dominikoeh** [comment]
Generated sample data:
[MaterialFlowSimulationResult-sample.json.txt](https://github.com/eclipse-tractusx/sldt-semantic-models/files/11170183/MaterialFlowSimulationResult-sample.json.txt)

**Comment by TobiasHamacherDLR** [comment]
MS2 Criteria
(to be filled out by PR reviewer)

- [x] the model validates with the BAMM SDS SDK in the version specified in the Readme.md of this repository by the time of the MS2 check (e.g., 'java -jar bamm-cli.jar -i <path-to-aspect-model> -v ). The BAMM CLI is available here and in GitHub
- [ ]  use Camel-Case (e.g., "MyModelElement" or "TimeDifferenceGmtId", when in doubt follow https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)
- [x]  the identifiers for all model elements start with a capital letter except for properties
- [x]  the identifier for properties starts with a small letter
- [ ]  all model elements at least contain the fields "name" and "description" in English language.
- [ ]  no duplicate names or preferredNames within an Aspect (e.g. a Property and the referenced Characteristic should not have the same name)
- [x]  the versioning in the URN follows semantic versioning, where minor version bumps are backwards compatible and major version bumps are not backwards compatible.
- [x]   use abbreviations only when necessary and if these are sufficiently common
- [x]  avoid redundant prefixes in property names (consider adding properties to an enclosing Entity or even adapt the namespace of the model elements, e.g., instead of having two properties DismantlerId and DismantlerName use an Entity Dismantler with the properties name and id or use a URN like io.catenax.dismantler:0.0.1)
- [x]  fields preferredName and description are not the same
- [x]  preferredName should be human readable and follow normal orthography (e.g., no camel case but normal word separation)
- [x]  name of aspect is singular except if it only has one property which is a Collection, List or Set. In theses cases, the aspect name is plural.
- [x]  units are referenced from the BAMM unit catalog whenever possible
- [x] use constraints to make known constraints from the use case explicit in the aspect model
- [x] when relying on external standards, they are referenced through a "see" element
- [x]  all properties with an simple type have an example value
- [x]  metadata.json exists with status "release"
- [x]  file RELEASE_NOTES.md exists and contains entries for proposed model changes

**Comment by TobiasHamacherDLR** [comment]
- BPNS CamelCase? => Bpns
```
Now lowercase everything (including acronyms), then uppercase only the first character of:
... each word, to yield upper camel case, or
... each word except the first, to yield lower camel case
```
@modeling_team Was not applied in the case of other models?

- "description" missing on most Entitys

- many propertys and characteristics have the same name, e.g., dataQuality, add Characteristic postfix =>dataQualityCharacteristic

**Comment by TobiasHamacherDLR** [comment]
modeling_team

**Comment by dominikoeh** [comment]
Latest sample data

[materialflowsimulationresult.json.txt](https://github.com/eclipse-tractusx/sldt-semantic-models/files/11200840/materialflowsimulationresult.json.txt)

**Comment by dominikoeh** [comment]
> * BPNS CamelCase? => Bpns
> 
> ```
> Now lowercase everything (including acronyms), then uppercase only the first character of:
> ... each word, to yield upper camel case, or
> ... each word except the first, to yield lower camel case
> ```
> 
> @modeling_team Was not applied in the case of other models?
> 
> * "description" missing on most Entities
> * many propertys and characteristics have the same name, e.g., dataQuality, add Characteristic postfix =>dataQualityCharacteristic

As suggested: BPNS references have been removed from the model in favor of more general site identifiers, `BusinessPartnerSite`, which could also be BPNS, but are not required to be.

**Review by bs-jokri — APPROVED** [review]
Thanks for the clarification. LGTM

**Pull request merged**
